 Not Found: /favicon.ico - 2024-11-11 11:44:32,305 - WARNING  
 Code Generated successfully...  - 2024-11-11 11:45:31,728 - INFO  
  user bepiwin327@anypng.com is registered with email bepiwin327@anypng.com successfully... - 2024-11-11 11:45:31,733 - INFO  
 Failed to send email to bepiwin327@anypng.com - 2024-11-11 11:45:31,764 - INFO  
 varifying the email bepiwin327@anypng.com - 2024-11-11 11:45:31,764 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 11:46:52,122 - INFO  
 bepiwin327@anypng.com logging successfully... - 2024-11-11 11:47:31,299 - INFO  
 Code Generated successfully...  - 2024-11-11 11:51:21,890 - INFO  
  user siwat61100@anypng.com is registered with email siwat61100@anypng.com successfully... - 2024-11-11 11:51:21,898 - INFO  
 Verification email send to siwat61100@anypng.com - 2024-11-11 11:51:25,509 - INFO  
 varifying the email siwat61100@anypng.com - 2024-11-11 11:51:25,509 - INFO  
  siwat61100@anypng.com verified Successfully... - 2024-11-11 11:53:57,873 - INFO  
 siwat61100@anypng.com logging successfully... - 2024-11-11 11:54:09,650 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 11:55:45,739 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 11:56:02,411 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 11:56:10,329 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 11:56:17,587 - INFO  
 D:\project final year\genai\chatbot\urls.py changed, reloading. - 2024-11-11 11:57:45,845 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 11:58:01,512 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 11:58:08,361 - INFO  
 D:\project final year\genai\chatbot\urls.py changed, reloading. - 2024-11-11 11:58:22,508 - INFO  
 D:\project final year\genai\chatbot\urls.py changed, reloading. - 2024-11-11 11:58:39,522 - INFO  
 siwat61100@anypng.com logging successfully... - 2024-11-11 11:59:27,994 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:00:01,552 - INFO  
 siwat61100@anypng.com logging successfully... - 2024-11-11 12:00:53,081 - INFO  
 siwat61100@anypng.com logging successfully... - 2024-11-11 12:01:40,726 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:01:54,845 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:05:59,835 - INFO  
 D:\project final year\genai\chatbot\admin.py changed, reloading. - 2024-11-11 12:23:09,707 - INFO  
 D:\project final year\genai\chatbot\admin.py changed, reloading. - 2024-11-11 12:23:19,521 - INFO  
 D:\project final year\genai\chatbot\admin.py changed, reloading. - 2024-11-11 12:24:23,288 - INFO  
 D:\project final year\genai\chatbot\admin.py changed, reloading. - 2024-11-11 12:24:43,082 - INFO  
 D:\project final year\genai\chatbot\admin.py changed, reloading. - 2024-11-11 12:25:06,182 - INFO  
 tayyab.khan14389@gmail.com logging successfully... - 2024-11-11 12:29:13,706 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:31:16,565 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:31:16,685 - INFO  
 Log out Complete... - 2024-11-11 12:31:24,239 - INFO  
 tayyab.khan14389@gmail.com logging successfully... - 2024-11-11 12:31:56,642 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:38:12,366 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:38:12,379 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:38:33,694 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:38:34,341 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:38:51,454 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:38:51,726 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:39:22,045 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:39:22,108 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:39:35,128 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:39:35,642 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:40:08,004 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:40:08,024 - INFO  
 Internal Server Error: /bot - 2024-11-11 12:41:44,119 - ERROR  
Traceback (most recent call last):
  File "D:\project final year\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\genai\chatbot\views.py", line 209, in bot
    chat_history = History.objects.filter(user=user)
                                               ^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:42:18,447 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:42:18,447 - INFO  
 Internal Server Error: /bot - 2024-11-11 12:42:24,246 - ERROR  
Traceback (most recent call last):
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endwith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project final year\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\genai\chatbot\views.py", line 211, in bot
    return render(request, 'bot.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 563, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 228: 'endwith', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
 Log out Complete... - 2024-11-11 12:42:25,015 - INFO  
 tayyab.khan14389@gmail.com logging successfully... - 2024-11-11 12:42:34,308 - INFO  
 Internal Server Error: /bot - 2024-11-11 12:42:34,521 - ERROR  
Traceback (most recent call last):
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endwith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project final year\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\genai\chatbot\views.py", line 211, in bot
    return render(request, 'bot.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\project final year\env\Lib\site-packages\django\template\base.py", line 563, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 228: 'endwith', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:44:14,486 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:44:14,666 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:44:23,288 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:44:24,037 - INFO  
 Error in bot view: finish_reason: RECITATION
index: 0
 - 2024-11-11 12:47:00,181 - ERROR  
 Internal Server Error: /bot - 2024-11-11 12:47:00,263 - ERROR  
Traceback (most recent call last):
  File "D:\project final year\genai\chatbot\views.py", line 182, in bot
    bot_response = gemini_response(user_message)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\genai\chatbot\views.py", line 155, in gemini_response
    response = chat_session.send_message(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\google\generativeai\generative_models.py", line 588, in send_message
    self._check_response(response=response, stream=stream)
  File "D:\project final year\env\Lib\site-packages\google\generativeai\generative_models.py", line 616, in _check_response
    raise generation_types.StopCandidateException(response.candidates[0])
google.generativeai.types.generation_types.StopCandidateException: finish_reason: RECITATION
index: 0


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project final year\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\genai\chatbot\views.py", line 210, in bot
    'chat_history':chat_history
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'chat_history' where it is not associated with a value
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:47:48,872 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:47:49,130 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:47:59,438 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:48:00,238 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:48:07,869 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:48:08,633 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:48:15,651 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:48:15,884 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:48:44,198 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:48:44,240 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:48:52,397 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:48:53,066 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:49:01,636 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-11 12:49:02,028 - INFO  
 Log out Complete... - 2024-11-11 12:50:20,481 - INFO  
 siwat61100@anypng.com logging successfully... - 2024-11-11 12:50:29,400 - INFO  
 Log out Complete... - 2024-11-11 12:51:40,835 - INFO  
 112211naseebjan321@gmail.com logging successfully... - 2024-11-11 12:51:57,395 - INFO  
 Log out Complete... - 2024-11-11 12:52:45,165 - INFO  
 tayyab.khan14389@gmail.com logging successfully... - 2024-11-11 19:34:41,548 - INFO  
 Not Found: /favicon.ico - 2024-11-12 21:19:34,975 - WARNING  
 tayyab.khan14389@gmail.com logging successfully... - 2024-11-12 21:20:14,995 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:22:09,277 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:24:56,723 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:25:02,386 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:25:08,324 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:25:21,821 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:25:27,676 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:25:33,281 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:25:42,513 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:25:49,076 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:26:25,524 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:26:35,427 - INFO  
 Internal Server Error: /bot - 2024-11-12 21:26:49,892 - ERROR  
Traceback (most recent call last):
  File "D:\project final year\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project final year\genai\chatbot\views.py", line 172, in bot
    chat_history = History.objects.filter(user=user)
                                               ^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:27:05,400 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:27:43,600 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:27:50,026 - INFO  
 D:\project final year\genai\chatbot\views.py changed, reloading. - 2024-11-12 21:27:55,772 - INFO  
